name: Auto Release on Push

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  bump-and-release:
    runs-on: ubuntu-latest
    if: "github.actor != 'github-actions[bot]'"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ensure scripts are executable
        run: |
          python -V

      - name: Bump version
        id: bump
        run: |
          python scripts/bump_version.py Mods/TweaksAndStuff/modinfo.json > new_version.txt
          echo "new_version=$(cat new_version.txt)" >> $GITHUB_OUTPUT

      - name: Commit bumped version
        env:
          NEW_VERSION: ${{ steps.bump.outputs.new_version }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Mods/TweaksAndStuff/modinfo.json
          git commit -m "Bump TweaksAndStuff to v${NEW_VERSION} [skip ci]" || echo "no changes to commit"
          git push origin HEAD:main || echo "push failed"

      - name: Create tag
        env:
          NEW_VERSION: ${{ steps.bump.outputs.new_version }}
        run: |
          TAG="v${NEW_VERSION}"
          git tag -a "$TAG" -m "Release $TAG" || echo "tag exists"
          git push origin "$TAG" || echo "push tag failed"

      - name: Create release and upload zip
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: v${{ steps.bump.outputs.new_version }}
          release_name: TweaksAndStuff v${{ steps.bump.outputs.new_version }}
          body: Automated release generated by workflow
          draft: false
          prerelease: false

      - name: Zip mod folder
        run: |
          mkdir -p release
          zip -r "release/tweaksandstuff-${{ steps.bump.outputs.new_version }}.zip" Mods/TweaksAndStuff

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/tweaksandstuff-${{ steps.bump.outputs.new_version }}.zip
          asset_name: tweaksandstuff-${{ steps.bump.outputs.new_version }}.zip
          asset_content_type: application/zip
